### ISSUE TITLE
Incompatible library version of libswiftCore.dylib

### ISSUE THREAD

**Issue by julianoes** [dronecore/DroneCore-Swift#30]
I'm using:
macOS 10.13.4 High Sierra
XCode 9.3 with Toolchain: Swift 4.0.3.

`pod install` worked and the build works as well but on loading I get:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib

  Referenced from: /private/var/containers/Bundle/Application/A4A675F3-41DB-46DD-97EA-D60F1D64ADB0/DronecodeSDKSwiftDemo.app/Frameworks/SwiftProtobufPluginLibrary.framework/SwiftProtobufPluginLibrary

  Reason: Incompatible library version: SwiftProtobufPluginLibrary requires version 1.0.0 or later, but libswiftCore.dylib provides version 0.0.0
```

I've tried deleting all of `DerivedData` and clean building without success.

**Comment by julianoes** [comment]
Using XCode 9.2 it works.

**Comment by JonasVautherin** [comment]
Closing, as I think we all managed to build/run the code on High Sierra with Xcode 9.3 by now.
