### ISSUE TITLE
Show mission on the map

### ISSUE THREAD

**Issue by JonasVautherin** [dronecore/DroneCore-Swift#48]
Would be nice to show, on the map, the mission that the sample app will upload to the drone.

@ayameMBS Is it a reasonably easy thing to do?

**Comment by ayameMBS** [comment]
@JonasVautherin yep there is a branch sample-show-mission. for now this is only an orange trace, but I will add a start and stop flag

**Comment by JonasVautherin** [comment]
Perfect! Feel free to open a PR whenever you feel it can be merged!
